version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - SECRET_KEY= 'django-insecure-nyd96_ktm^_so3^_po%4pb8h@1em7!l@_$y9nqp_#9^4tlrpt^'
      - DEBUG=False
      - DATABASE_URL=sqlite:///db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build:
      context: .
